apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    hpc.scch.at/responsibility: urbanke
spec:
  selector:
    matchLabels:
      app: otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        hpc.scch.at/responsibility: urbanke
        hpc.scch.at/service: otel-collector
        app: otel-collector
    spec:
      imagePullSecrets:
        - name: conregscch
      containers:
        - name: otel-collector
          image: containers.github.scch.at/contest/trainticket/slotel-collector:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c", 'cd /slotel/; java -jar TraceCollector-1.0.jar -t traces.txt -m PUSH -p 4242 -f "\"http.status_code\":2"' ]
          ports:
            - containerPort: 4242
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 4000m
              memory: 4000Mi
          readinessProbe:
            tcpSocket:
              port: 4242
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4242
      protocol: TCP
      targetPort: 4242
  selector:
    app: otel-collector
