name: Deploy to local minikube

on:
  workflow_dispatch:
    inputs:
      chosen-runner:
        required: false
        type: choice
        description: 'Runner label'
        default: 'austin'
        options:
          - local-runner
          - austin
          - march
      namespace:
        required: false
        type: text
        description: 'Kubernetes namespace'
        default: 'default'
      deploy-args:
        required: true
        type: choice
        description: 'Deployment arguments'
        default: '--with-otel --with-monitoring'
        options:
#          - --independent-db
#          - --with-monitoring
#          - --with-tracing
#          - --with-otel
#          - --independent-db --with-tracing
#          - --independent-db --with-monitoring
#          - --independent-db --with_otel
#          - --with-otel --with-tracing
          - --with-otel --with-monitoring
#          - --with-tracing --with-monitoring
#          - --with-tracing --with-monitoring --with_otel
#          - --all

jobs:
  deploy:
    runs-on: [ self-hosted, "${{ inputs.chosen-runner }}" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            deployment
            hack

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: containers.github.scch.at
          username: ${{ github.actor }}
          password: ${{ github.token }}


      - name: Set paths and execute deployment script
        run: |
          kubectl config use-context docker-desktop
          ./hack/deploy/deploy.sh "${{ inputs.namespace }}" "${{ inputs.deploy-args }}"
