apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18767
      nodePort: 30030
  selector:
    app: ts-admin-basic-info-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-order-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16112
      nodePort: 30031
  selector:
    app: ts-admin-order-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-route-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16113
      nodePort: 30032
  selector:
    app: ts-admin-route-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-travel-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16114
      nodePort: 30033
  selector:
    app: ts-admin-travel-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-user-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16115
      nodePort: 30034
  selector:
    app: ts-admin-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18888
      nodePort: 30035
  selector:
    app: ts-assurance-service
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ts-auth-service
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      port: 12340
#      nodePort: 30000
#  selector:
#    app: ts-auth-service
#---
apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 15680
      nodePort: 30038
  selector:
    app: ts-basic-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-cancel-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18885
      nodePort: 30039
  selector:
    app: ts-cancel-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 15679
      nodePort: 30040
  selector:
    app: ts-config-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16110
      nodePort: 30041
  selector:
    app: ts-consign-price-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-consign-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16111
      nodePort: 30042
  selector:
    app: ts-consign-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12347
      nodePort: 30043
  selector:
    app: ts-contacts-service
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ts-delivery-service
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      port: 18808
#      nodePort: 30044
#  selector:
#    app: ts-delivery-service
#---
apiVersion: v1
kind: Service
metadata:
  name: ts-execute-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12386
      nodePort: 30045
  selector:
    app: ts-execute-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-food-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18856
      nodePort: 30046
  selector:
    app: ts-food-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18673
      nodePort: 30047
  selector:
    app: ts-inside-payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-news-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12862
      nodePort: 30048
  selector:
    app: ts-news-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-notification-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 17853
      nodePort: 30049
  selector:
    app: ts-notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12032
      nodePort: 30050
  selector:
    app: ts-order-other-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12031
      nodePort: 30051
  selector:
    app: ts-order-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-payment-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 19001
      nodePort: 30052
  selector:
    app: ts-payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-other-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 14569
      nodePort: 30053
  selector:
    app: ts-preserve-other-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 14568
      nodePort: 30054
  selector:
    app: ts-preserve-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16579
      nodePort: 30055
  selector:
    app: ts-price-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-rebook-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18886
      nodePort: 30056
  selector:
    app: ts-rebook-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-plan-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 14578
      nodePort: 30057
  selector:
    app: ts-route-plan-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 11178
      nodePort: 30058
  selector:
    app: ts-route-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-seat-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18898
      nodePort: 30059
  selector:
    app: ts-seat-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-security-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 11188
      nodePort: 30060
  selector:
    app: ts-security-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12345
      nodePort: 30062
  selector:
    app: ts-station-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16108
      nodePort: 30063
  selector:
    app: ts-ticket-office-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 14567
      nodePort: 30065
  selector:
    app: ts-train-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-plan-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 14322
      nodePort: 30066
  selector:
    app: ts-travel-plan-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12346
      nodePort: 30067
  selector:
    app: ts-travel-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 16346
      nodePort: 30068
  selector:
    app: ts-travel2-service
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ts-user-service
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      port: 12342
#      nodePort: 30069
#  selector:
#    app: ts-user-service
#---
apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 15678
      nodePort: 30070
  selector:
    app: ts-verification-code-service
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ts-voucher-service
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      port: 16101
#      targetPort: 16101
#      nodePort: 30071
#  selector:
#    app: ts-voucher-service
#---
apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32677
  selector:
    app: ts-ui-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18855
      nodePort: 30072
  selector:
    app: ts-food-map-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 15681
      nodePort: 30073
  selector:
    app: ts-ticketinfo-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-login-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12342
      nodePort: 30074
  selector:
    app: ts-login-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12349
      nodePort: 30075
  selector:
    app: ts-sso-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-register-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12344
      nodePort: 30076
  selector:
    app: ts-register-service
---